[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "aposteriori"
version = "2.5.0"
requires-python = ">= 3.8"
readme = "README.md"
dependencies = [
    "ampal",
    "click",
    "h5py",
    "numpy<2.0.0",
    "flake8",
    "psutil",
    "tqdm",

    ]

[project.scripts]
make-frame-dataset = "aposteriori.data_prep.cli:cli"
